# Generated by Django 5.1.4 on 2025-01-29 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, default='none', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('unit_type', models.CharField(choices=[('units', 'Unidades'), ('lbs', 'Libras'), ('paqs', 'Paquetes')], max_length=10)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='/default.png', null=True, upload_to='product_images/')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop')),
            ],
        ),
    ]
