# Generated by Django 5.1.4 on 2025-02-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#d5e4ff', 'blue'), ('#ffe3e7', 'pink'), ('#ccffc4', 'green'), ('#eeff86', 'yellow'), ('#ffdddd', 'red')], max_length=10, verbose_name='Color de etiqueta'),
        ),
    ]
