# Generated by Django 5.1.4 on 2025-02-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('#d5e4ff', 'blue'), ('#ffe3e7', 'pink'), ('#ccffc4', 'green'), ('#eeff86', 'yellow'), ('#ffdddd', 'red')], max_length=10, null=True, verbose_name='Color de etiqueta'),
        ),
    ]
