# Generated by Django 5.1.4 on 2025-01-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='inventories', to='api.product'),
        ),
    ]
