# Generated by Django 5.1.4 on 2025-01-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_inventory_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='contact_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
