# Generated by Django 5.1.4 on 2025-01-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shop_contact_number_shop_image_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default='shop_images/image_default.webp', null=True, upload_to='shop_images/'),
        ),
    ]
